# Generated by Django 3.0.3 on 2020-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0004_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NA', 'Not_Arrived'), ('AR', 'Arrived')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('NS', 'NOTSALE'), ('S', 'SALE')], default='NS', max_length=2),
            preserve_default=False,
        ),
    ]
