# Generated by Django 3.0.3 on 2020-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0005_auto_20200418_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='buy_by_user',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
