# Generated by Django 3.0.3 on 2020-04-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0008_auto_20200419_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
