# Generated by Django 3.0.3 on 2020-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0015_auto_20200419_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('S', 'SALE'), ('NS', 'NOTSALE')], max_length=2),
        ),
    ]
