# Generated by Django 3.0.3 on 2020-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0017_auto_20200419_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NA', 'Not_Arrived'), ('AR', 'Arrived')], max_length=2),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('S', 'SALE'), ('NS', 'NOTSALE')], max_length=2),
        ),
    ]
