# Generated by Django 3.0.3 on 2020-04-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0019_auto_20200419_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
