# Generated by Django 3.0.3 on 2020-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0021_auto_20200419_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NA', 'Not_Arrived'), ('AR', 'Arrived')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('NS', 'NOTSALE'), ('S', 'SALE')], max_length=2),
        ),
    ]
