# Generated by Django 3.0.3 on 2020-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0023_auto_20200419_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('AR', 'Arrived'), ('NA', 'Not_Arrived')], max_length=2),
        ),
    ]
