# Generated by Django 3.0.3 on 2020-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0037_auto_20200423_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promotion_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('S', 'SALE'), ('NS', 'NOTSALE')], max_length=2),
        ),
    ]
