# Generated by Django 3.0.3 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0039_auto_20200426_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('NS', 'NOTSALE'), ('S', 'SALE')], max_length=2),
        ),
    ]
