# Generated by Django 3.0.3 on 2020-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0041_auto_20200426_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_promotion',
            field=models.CharField(choices=[('NS', 'NOTSALE'), ('S', 'SALE')], max_length=2),
        ),
    ]
